### ISSUE TITLE
关于不支持非arm架构

### ISSUE THREAD

**Issue by yjm484** [NaNExist/ResonanceAssistant#10]
本人对于adb、图像识别等几乎一窍不通，想了解下不支持非arm架构的原因或者说问题点在哪里。是因为adb的问题吗，还是其他，如能满足在下好奇心，不胜感激。

**Comment by NaNExist** [comment]
没有任何原因~~只是我太懒也太菜了~~
而且也不是说不支持，是没做对应的Release
因为我没写自动部署，每次的Release版本都是我手动操作的
如果需要的话我现在就上一个

**Comment by NaNExist** [comment]
现在上了一个win的aarch64的Release

其实最大问题是两个，一个是我自己没有对应平台也技术不会测试在对应平台下能不能测试，另外一个目前还没有多少人用这个，也没有对应的反馈

底层架构应该是没有问题的（当然模拟器本身能不能跑就是另外一个问题了

**Comment by yjm484** [comment]
笑死，我脑海里已经在想这是什么苦大仇深的问题吗，厂商之间竞争之类，搜了搜也没搜到什么。那顺便一问，截图的维妮塔是跟arm架构有关吗？我的cpu是amd5600x，似乎并不是arm架构的。port看着也没问题，不知道还能配置什么参数了
![微信截图_20240308233352](https://github.com/NaNExist/ResonanceAssistant/assets/53459430/70d4e90a-d38d-480a-b8f2-a1e83b64bd33)

**Comment by yjm484** [comment]
我家网络或者git好像有点抽风，现在新的release下不下来，我明天来反馈吧

**Comment by NaNExist** [comment]
> 笑死，我脑海里已经在想这是什么苦大仇深的问题吗，厂商之间竞争之类，搜了搜也没搜到什么。那顺便一问，截图的报错是跟arm架构有关吗？我的cpu是amd5600x，似乎并不是arm架构的。port看着也没问题，不知道还能配置什么参数了
> ![微信截图_20240308233352](https://github.com/NaNExist/ResonanceAssistant/assets/53459430/70d4e90a-d38d-480a-b8f2-a1e83b64bd33)
> 

好像是没连上模拟器

顺便我忘记在使用说明里面写分辨率要设置为1280*720才能运行了

我的锅

**Comment by NaNExist** [comment]
> > 笑死，我脑海里已经在想这是什么苦大仇深的问题吗，厂商之间竞争之类，搜了搜也没搜到什么。那顺便一问，截图的报错是跟arm架构有关吗？我的cpu是amd5600x，似乎并不是arm架构的。port看着也没问题，不知道还能配置什么参数了
> > ![微信截图_20240308233352](https://github.com/NaNExist/ResonanceAssistant/assets/53459430/70d4e90a-d38d-480a-b8f2-a1e83b64bd33)
> > 
> 
> 好像是没连上模拟器
> 
> 顺便我忘记在使用说明里面写分辨率要设置为1280*720才能运行了
> 
> 我的锅

以及5600x依然是x86的架构，用X86的就行

**Comment by yjm484** [comment]
使用x86改成1280*720还是同样的报错，模拟器是mumu12
![微信截图_20240309172604](https://github.com/NaNExist/ResonanceAssistant/assets/53459430/3f9da72e-172e-4fac-9bf9-55c86b24ff31)

**Comment by NaNExist** [comment]
> 使用x86改成1280*720还是同样的报错，模拟器是mumu12 ![微信截图_20240309172604](https://private-user-images.githubusercontent.com/53459430/311427889-3f9da72e-172e-4fac-9bf9-55c86b24ff31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5ODg3OTYsIm5iZiI6MTcwOTk4ODQ5NiwicGF0aCI6Ii81MzQ1OTQzMC8zMTE0Mjc4ODktM2Y5ZGE3MmUtMTcyZS00ZmFjLTliZjktNTVjODZiMjRmZjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDEyNDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NDI4MTc4NDE5OTcyYzc1Yjc5Y2Y3NjI0ZGJiODM0M2RhN2MzYmZlMGY2YjdjYjIxYjBjMDQ2M2RmMWIzNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZL_AxVZdsSCvTOkGyF1R3oLDWjlF-Pgyo0r7qpkUPow)

你选择输入1 Switch Controller 然后接着选择1 Auto Detect重新自动识别模拟器
这个好像是我的模拟器配置 v0.2.0的Release忘记删了 绷不住了
或者你直接下新的v0.2.1的版本

**Comment by yjm484** [comment]
![微信截图_20240311003226](https://github.com/NaNExist/ResonanceAssistant/assets/53459430/fcbaf350-c562-41f0-85b4-762dee79de2a)
![微信截图_20240311003641](https://github.com/NaNExist/ResonanceAssistant/assets/53459430/3d8065af-b9de-4227-a2b3-82e014801bec)

使用了最新的版本，这是什么问题呢，难道是我本地同时存在老版mumu和mumu12的问题吗，或者我电脑里面的adb太多了？

**Comment by NaNExist** [comment]
不知道又是什么bug呢，建议每次只开一个模拟器

**Comment by Shaw-W** [comment]
aarch64已发release，此issue关闭，其他问题请提新issue

https://github.com/NaNExist/ResonanceAssistant/releases/tag/v0.2.6-beta
