### ISSUE TITLE
[Feature Request] 建议将开发仓库和本仓库合并

### ISSUE THREAD

**Issue by Shaw-W** [NaNExist/ResonanceAssistant#18]
看了下 https://github.com/NaNExist/RA-deploy 这个项目的代码结构，其实那边就是多了些部署相关的东西，本质上还是引用了这边的资源文件。
个人建议可以合并俩个仓库，以便于后续ci/cd的开发，同时也方便发布，不需要维护两个仓库。

**Comment by NaNExist** [comment]
说的很好，立马开始着手做!
因为第一次做开源项目确实很不熟

**Comment by NaNExist** [comment]
已完成
