### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by fatinghenji** [NaNExist/ResonanceAssistant#32]
![image](https://github.com/NaNExist/ResonanceAssistant/assets/37131177/a619f89a-ad08-41e1-ab53-55e723fc70cf)
```
版本	Windows 11 专业版
版本	23H2
安装日期	‎2024/‎3/‎17
操作系统版本	22631.2861
体验	Windows Feature Experience Pack 1000.22681.1000.0
```
版本：RAA-win-x86_64-v0.2.7-alpha1.zip

**Comment by NaNExist** [comment]
CPU型号？建议你试一下aarch64的Release

**Comment by fatinghenji** [comment]
> CPU型号？建议你试一下aarch64的Release

13th Gen Intel(R) Core(TM) i5-13600KF   3.50 GHz

**Comment by fatinghenji** [comment]
maa可以正常运行。`aarch64`也没办法运行

**Comment by NaNExist** [comment]
> maa可以正常运行。`aarch64`也没办法运行
> `v0.2.7-alpha2`同样问题

现在auto release有点问题，等修复吧

**Comment by Shaw-W** [comment]
检查为github workflows新版本编译环境有问题，会导致架构不匹配，现已暂时回滚，下载新包即可解决问题
